name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:25

    steps:
    - uses: actions/checkout@v3
    - name: Check format
      run: rebar3 fmt --check
    - name: Compile
      run: rebar3 compile
    - name: Self-link
      run: "mkdir _checkouts && ln -s .. _checkouts/exerl"
    - name: Run tests
      run: rebar3 do eunit, ct
